### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by botandrose** [DatabaseCleaner/database_cleaner-mongo_mapper#1]
@etagwerker I think this is the only remaining retired adapter repo that is still unarchived. Wanna archive this one as well?

**Comment by JonRowe** [comment]
👍👍 as it sent me another security alert today :joy:

**Comment by etagwerker** [comment]
@botandrose Will do that. 👍 

@JonRowe Thanks for the reminder! I had missed this issue. 😸
